import type { KnowledgeSystemDefinition } from "./types";
import { RAG_CONTRACT_PATH } from "../constants";

export const KNOWLEDGE_DISCOVERY_EXCLUDED_FILE_PATTERNS = [
  "dop_assistant_spec_package/",
  "arab-stylist-studio-spec/",
  "scripts/lint-chunked.mjs",
  "scripts/run-vitest-chunks.mjs",
];

export const KNOWLEDGE_SYSTEM_DEFINITIONS: KnowledgeSystemDefinition[] = [
  {
    id: "workspace-embeddings",
    label: "Workspace Code Embeddings",
    category: "code-retrieval",
    policy: "govern-only",
    root: "scripts",
    description:
      "Live agent code memory with LanceDB local storage and optional Qdrant sync.",
    commands: [
      "pnpm workspace:embed",
      "pnpm agent:memory:index",
      "pnpm agent:memory:search",
      "pnpm agent:memory:status",
      "pnpm agent:memory:verify",
      "pnpm agent:memory:watch",
      "pnpm agent:guard:step",
    ],
    entrypoints: [
      "scripts/generate-workspace-embeddings.js",
      "scripts/agent/guard.ts",
      "scripts/agent/code-memory-index.ts",
      "scripts/agent/code-memory-search.ts",
      "scripts/agent/code-memory-status.ts",
      "scripts/agent/code-memory-verify.ts",
      "scripts/agent/code-memory-watch.ts",
    ],
    criticalFiles: [
      "scripts/generate-workspace-embeddings.js",
      "scripts/agent/guard.ts",
      "scripts/agent/code-memory-index.ts",
      "scripts/agent/code-memory-search.ts",
      "scripts/agent/code-memory-status.ts",
      "scripts/agent/code-memory-verify.ts",
      "scripts/agent/code-memory-watch.ts",
      "scripts/agent/lib/agent-guard.ts",
      "scripts/agent/lib/code-memory/config.ts",
      "scripts/agent/lib/code-memory/discovery.ts",
      "scripts/agent/lib/code-memory/embedder.ts",
      "scripts/agent/lib/code-memory/store.ts",
      "scripts/agent/lib/code-memory/qdrant.ts",
      "scripts/agent/lib/code-memory/status.ts",
      "scripts/agent/lib/code-memory/commands.ts",
      "WORKSPACE-EMBEDDING-INDEX.json",
      "WORKSPACE-EMBEDDING-SUMMARY.md",
      ".embedding-hash-cache.json",
      ".agent-code-memory/manifest.json",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "package.json",
      "pnpm-workspace.yaml",
      "scripts/generate-workspace-embeddings.js",
      "scripts/agent/lib/code-memory/*",
      "apps/*",
      "packages/*",
    ],
    artifacts: [
      ".agent-code-memory/",
      "WORKSPACE-EMBEDDING-INDEX.json",
      "WORKSPACE-EMBEDDING-SUMMARY.md",
      ".embedding-hash-cache.json",
    ],
    dependencies: [
      "Google Gemini embeddings",
      "LanceDB",
      "Qdrant",
      "pnpm workspace:embed",
    ],
    components: [
      { kind: "entrypoint", path: "scripts/generate-workspace-embeddings.js" },
      { kind: "entrypoint", path: "scripts/agent/guard.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-index.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-search.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-status.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-verify.ts" },
      { kind: "entrypoint", path: "scripts/agent/code-memory-watch.ts" },
      { kind: "chunking", path: "scripts/agent/lib/code-memory/discovery.ts" },
      {
        kind: "embedding-generation",
        path: "scripts/agent/lib/code-memory/embedder.ts",
      },
      { kind: "indexing", path: "scripts/agent/lib/code-memory/store.ts" },
      { kind: "vector-store", path: "scripts/agent/lib/code-memory/store.ts" },
      { kind: "vector-store", path: "scripts/agent/lib/code-memory/qdrant.ts" },
      { kind: "search", path: "scripts/agent/lib/code-memory/commands.ts" },
      { kind: "governance", path: "scripts/agent/lib/agent-guard.ts" },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: [
      "scripts/generate-workspace-embeddings.js",
      "scripts/agent/code-memory-",
      "scripts/agent/lib/code-memory/",
      ".agent-code-memory/",
      "WORKSPACE-EMBEDDING-INDEX.json",
      "WORKSPACE-EMBEDDING-SUMMARY.md",
      ".embedding-hash-cache.json",
    ],
    localDocPaths: [],
    providerPatterns: ["gemini-embedding-001", "GoogleGenAI"],
    vectorStorePatterns: [
      "LanceDB",
      "lancedb",
      "Qdrant",
      "qdrant",
      "WORKSPACE-EMBEDDING-INDEX.json",
      ".agent-code-memory",
    ],
    rerankerPatterns: [],
    allowMultipleVectorStores: true,
  },
  {
    id: "backend-memory",
    label: "Backend Memory Retrieval",
    category: "vector-memory",
    policy: "unify-now",
    root: "apps/backend/src/memory",
    description:
      "Unified repository indexing, Weaviate retrieval, and profile-based context assembly.",
    commands: [],
    entrypoints: [
      "apps/backend/src/memory/index.ts",
      "apps/backend/src/memory/api/routes.ts",
    ],
    criticalFiles: [
      "apps/backend/src/memory/index.ts",
      "apps/backend/src/memory/api/routes.ts",
      "apps/backend/src/memory/embeddings/generator.ts",
      "apps/backend/src/memory/embeddings/mrl-optimizer.ts",
      "apps/backend/src/memory/indexer/repository-crawler.ts",
      "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      "apps/backend/src/memory/indexer/git-watcher.ts",
      "apps/backend/src/memory/context/context-assembly.service.ts",
      "apps/backend/src/memory/retrieval/context-builder.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      "apps/backend/src/memory/vector-store/client.ts",
      "apps/backend/src/memory/vector-store/schema.ts",
      "apps/backend/src/memory/types.ts",
      "packages/core-memory/src/chunking/semanticChunker.ts",
      "packages/core-memory/src/types.ts",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "apps/backend/src/memory/index.ts",
      "apps/backend/src/memory/api/routes.ts",
      "packages/core-memory/src/chunking/semanticChunker.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
    ],
    artifacts: [
      "Weaviate:CodeChunks",
      "Weaviate:Documentation",
      "Weaviate:Decisions",
      "Weaviate:Architecture",
      "Weaviate:AdHocChunks",
    ],
    dependencies: [
      "Weaviate",
      "Google Gemini embeddings",
      "@the-copy/core-memory",
    ],
    components: [
      { kind: "entrypoint", path: "apps/backend/src/memory/index.ts" },
      { kind: "api", path: "apps/backend/src/memory/api/routes.ts" },
      {
        kind: "embedding-generation",
        path: "apps/backend/src/memory/embeddings/generator.ts",
      },
      {
        kind: "embedding-generation",
        path: "apps/backend/src/memory/embeddings/mrl-optimizer.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/repository-crawler.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/git-watcher.ts",
      },
      {
        kind: "chunking",
        path: "packages/core-memory/src/chunking/semanticChunker.ts",
      },
      {
        kind: "context-assembly",
        path: "apps/backend/src/memory/context/context-assembly.service.ts",
      },
      {
        kind: "context-assembly",
        path: "apps/backend/src/memory/retrieval/context-builder.ts",
      },
      {
        kind: "retrieval",
        path: "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      },
      {
        kind: "vector-store",
        path: "apps/backend/src/memory/vector-store/client.ts",
      },
      {
        kind: "vector-store",
        path: "apps/backend/src/memory/vector-store/schema.ts",
      },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: ["apps/backend/src/memory/", "packages/core-memory/"],
    localDocPaths: [],
    providerPatterns: [
      "GoogleGenAI",
      "gemini-embedding-2-preview",
      "gemini-embedding-001",
    ],
    vectorStorePatterns: [
      "weaviate",
      "Weaviate",
      "CodeChunks",
      "Documentation",
      "Decisions",
      "Architecture",
      "AdHocChunks",
    ],
    rerankerPatterns: ["selectHits"],
  },
  {
    id: "backend-enhanced-rag",
    label: "Backend Enhanced RAG",
    category: "drama-retrieval",
    policy: "unify-now",
    root: "apps/backend/src/services/rag",
    description:
      "Coordinator facade over shared chunking, Weaviate retrieval, and unified context assembly.",
    commands: [],
    entrypoints: ["apps/backend/src/services/rag/enhancedRAG.service.ts"],
    criticalFiles: [
      "apps/backend/src/services/rag/enhancedRAG.service.ts",
      "apps/backend/src/services/rag/embeddings.service.ts",
      "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      "apps/backend/src/memory/context/context-assembly.service.ts",
      "apps/backend/src/memory/embeddings/generator.ts",
      "apps/backend/src/memory/vector-store/client.ts",
      "packages/core-memory/src/chunking/semanticChunker.ts",
      "packages/core-memory/src/types.ts",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "apps/backend/src/services/rag/enhancedRAG.service.ts",
      "apps/backend/src/services/rag/embeddings.service.ts",
      "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      "apps/backend/src/memory/context/context-assembly.service.ts",
    ],
    artifacts: ["Weaviate:AdHocChunks", "ContextAssemblyService output"],
    dependencies: [
      "Weaviate",
      "ContextAssemblyService",
      "Google Gemini embeddings",
    ],
    components: [
      {
        kind: "entrypoint",
        path: "apps/backend/src/services/rag/enhancedRAG.service.ts",
      },
      {
        kind: "embedding-generation",
        path: "apps/backend/src/services/rag/embeddings.service.ts",
      },
      {
        kind: "chunking",
        path: "packages/core-memory/src/chunking/semanticChunker.ts",
      },
      {
        kind: "indexing",
        path: "apps/backend/src/memory/indexer/weaviate-indexing.service.ts",
      },
      {
        kind: "retrieval",
        path: "apps/backend/src/memory/retrieval/weaviate-retrieval.service.ts",
      },
      {
        kind: "vector-store",
        path: "apps/backend/src/memory/vector-store/client.ts",
      },
      {
        kind: "context-assembly",
        path: "apps/backend/src/memory/context/context-assembly.service.ts",
      },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: ["apps/backend/src/services/rag/"],
    localDocPaths: [],
    providerPatterns: [
      "GoogleGenAI",
      "GoogleGenerativeAI",
      "gemini-embedding-2-preview",
      "gemini-embedding-001",
    ],
    vectorStorePatterns: [
      "weaviate",
      "Weaviate",
      "weaviateStore",
      "AdHocChunks",
    ],
    rerankerPatterns: ["selectHits"],
  },
  {
    id: "editor-code-rag",
    label: "Editor Code RAG",
    category: "code-retrieval",
    policy: "temporary-independent",
    root: "apps/web/src/app/(main)/editor",
    description:
      "Editor-local code retrieval using Qdrant for vectors, OpenRouter embeddings, and Gemini answers.",
    commands: [
      "pnpm --filter @the-copy/web editor:rag:index",
      "pnpm --filter @the-copy/web editor:rag:ask",
      "pnpm --filter @the-copy/web editor:rag:stats",
      "pnpm --filter @the-copy/web editor:rag:smoke",
    ],
    entrypoints: [
      "apps/web/src/app/(main)/editor/scripts/rag-index.ts",
      "apps/web/src/app/(main)/editor/scripts/rag-query.ts",
      "apps/web/src/app/(main)/editor/scripts/rag-stats.ts",
      "apps/web/src/app/(main)/editor/scripts/rag-smoke-test.ts",
    ],
    criticalFiles: [
      "apps/web/src/app/(main)/editor/scripts/rag-index.ts",
      "apps/web/src/app/(main)/editor/scripts/rag-query.ts",
      "apps/web/src/app/(main)/editor/scripts/rag-stats.ts",
      "apps/web/src/app/(main)/editor/scripts/rag-smoke-test.ts",
      "apps/web/src/app/(main)/editor/src/rag/chunker.ts",
      "apps/web/src/app/(main)/editor/src/rag/config.ts",
      "apps/web/src/app/(main)/editor/src/rag/embeddings.ts",
      "apps/web/src/app/(main)/editor/src/rag/indexer.ts",
      "apps/web/src/app/(main)/editor/src/rag/query.ts",
      "apps/web/src/app/(main)/editor/src/rag/types.ts",
      "apps/web/src/app/(main)/editor/src/rag/README.md",
      "apps/web/src/app/(main)/editor/src/rag/rag-system.md",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "apps/web/package.json",
      "apps/web/src/app/(main)/editor/scripts/rag-index.ts",
      "apps/web/src/app/(main)/editor/src/rag/config.ts",
      "apps/web/src/app/(main)/editor/src/rag/query.ts",
    ],
    artifacts: ["Qdrant:codebase-index"],
    dependencies: [
      "QDRANT_URL",
      "QDRANT_API_KEY",
      "OPENROUTER_API_KEY",
      "GEMINI_API_KEY",
    ],
    components: [
      {
        kind: "entrypoint",
        path: "apps/web/src/app/(main)/editor/scripts/rag-index.ts",
      },
      {
        kind: "entrypoint",
        path: "apps/web/src/app/(main)/editor/scripts/rag-query.ts",
      },
      {
        kind: "entrypoint",
        path: "apps/web/src/app/(main)/editor/scripts/rag-stats.ts",
      },
      {
        kind: "entrypoint",
        path: "apps/web/src/app/(main)/editor/scripts/rag-smoke-test.ts",
      },
      {
        kind: "chunking",
        path: "apps/web/src/app/(main)/editor/src/rag/chunker.ts",
      },
      {
        kind: "embedding-generation",
        path: "apps/web/src/app/(main)/editor/src/rag/embeddings.ts",
      },
      {
        kind: "indexing",
        path: "apps/web/src/app/(main)/editor/src/rag/indexer.ts",
      },
      {
        kind: "retrieval",
        path: "apps/web/src/app/(main)/editor/src/rag/query.ts",
      },
      {
        kind: "vector-store",
        path: "apps/web/src/app/(main)/editor/src/rag/config.ts",
      },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: [
      "apps/web/src/app/(main)/editor/scripts/rag-",
      "apps/web/src/app/(main)/editor/src/rag/",
    ],
    localDocPaths: [
      "apps/web/src/app/(main)/editor/src/rag/README.md",
      "apps/web/src/app/(main)/editor/src/rag/rag-system.md",
    ],
    providerPatterns: [
      "https://openrouter.ai/api/v1",
      "OPENROUTER_API_KEY",
      "GoogleGenAI",
      "GEMINI_API_KEY",
    ],
    vectorStorePatterns: ["qdrant", "Qdrant", "codebase-index"],
    rerankerPatterns: [],
    allowMultipleProviders: true,
  },
  {
    id: "web-legacy-rag",
    label: "Web Legacy RAG Utilities",
    category: "lightweight-search",
    policy: "do-not-force-merge",
    root: "apps/web/src/lib",
    description:
      "Legacy in-web chunking and retrieval helpers retained under governance without forced architectural merge.",
    commands: [],
    entrypoints: [
      "apps/web/src/lib/ai/rag/index.ts",
      "apps/web/src/lib/drama-analyst/services/ragService.ts",
    ],
    criticalFiles: [
      "apps/web/src/lib/ai/stations/gemini-service.ts",
      "apps/web/src/lib/ai/rag/context-retriever.ts",
      "apps/web/src/lib/ai/rag/index.ts",
      "apps/web/src/lib/ai/rag/text-chunking.ts",
      "apps/web/src/lib/ai/text-chunking.ts",
      "apps/web/src/lib/drama-analyst/agents/shared/standardAgentPattern.rag.ts",
      "apps/web/src/lib/drama-analyst/services/ragService.ts",
      RAG_CONTRACT_PATH,
    ],
    inputs: [
      "apps/web/src/lib/ai/rag/context-retriever.ts",
      "apps/web/src/lib/ai/rag/text-chunking.ts",
      "apps/web/src/lib/drama-analyst/agents/shared/standardAgentPattern.rag.ts",
      "apps/web/src/lib/drama-analyst/services/ragService.ts",
    ],
    artifacts: ["In-memory context maps", "In-memory retrieved chunks"],
    dependencies: ["GeminiService", "Frontend in-memory chunking"],
    components: [
      { kind: "entrypoint", path: "apps/web/src/lib/ai/rag/index.ts" },
      { kind: "chunking", path: "apps/web/src/lib/ai/rag/text-chunking.ts" },
      { kind: "chunking", path: "apps/web/src/lib/ai/text-chunking.ts" },
      {
        kind: "retrieval",
        path: "apps/web/src/lib/ai/rag/context-retriever.ts",
      },
      {
        kind: "retrieval",
        path: "apps/web/src/lib/drama-analyst/agents/shared/standardAgentPattern.rag.ts",
      },
      {
        kind: "retrieval",
        path: "apps/web/src/lib/drama-analyst/services/ragService.ts",
      },
      {
        kind: "embedding-generation",
        path: "apps/web/src/lib/ai/stations/gemini-service.ts",
      },
      { kind: "governance", path: RAG_CONTRACT_PATH },
    ],
    ownedPrefixes: [
      "apps/web/src/lib/ai/rag/",
      "apps/web/src/lib/ai/text-chunking.ts",
      "apps/web/src/lib/drama-analyst/services/ragService.ts",
    ],
    localDocPaths: [],
    providerPatterns: ["GeminiService", "geminiService"],
    vectorStorePatterns: [],
    rerankerPatterns: [],
  },
];
