import { useCallback, useRef } from "react";
import type { PersistedSelfTapeTake } from "../../../lib/self-tape";
import { pickSupportedMimeType } from "../../../lib/self-tape";

type CameraState = "idle" | "requesting" | "ready" | "error";
type NotificationState = {
  type: "success" | "error" | "info";
  message: string;
} | null;

interface TakeNote {
  id: string;
  timestamp: number;
  type: "emotion" | "delivery" | "timing" | "movement" | "improvement";
  content: string;
  severity: "positive" | "neutral" | "needs_work";
  autoGenerated: boolean;
}

interface Take extends PersistedSelfTapeTake {
  notes: TakeNote[];
  videoUrl?: string;
}

interface TeleprompterSettings {
  speed: number;
  fontSize: number;
  mirrorMode: boolean;
  highlightCurrentLine: boolean;
  autoScroll: boolean;
  countdownSeconds: number;
}

interface PendingTake {
  id: string;
  name: string;
  recordedAt: string;
  mimeType: string;
  teleprompterUsed: boolean;
}

const RECORDING_MIME_CANDIDATES = [
  "video/webm;codecs=vp9,opus",
  "video/webm;codecs=vp8,opus",
  "video/webm",
];

export const useCameraRecording = (
  showNotification: (type: "success" | "error" | "info", message: string) => void,
  scriptText: string,
  takes: Take[],
  teleprompterSettings: TeleprompterSettings,
  startTeleprompter: () => void,
  stopTeleprompter: () => void,
  markTakeExportable: (takeId: string) => void,
  setTakes: (takes: Take[] | ((prev: Take[]) => Take[])) => void,
  setNotesTakeId: (takeId: string | null) => void,
  setComparisonView: (view: any) => void,
  buildTakeInsights: (params: any) => any,
  createNotesFromInsights: (notes: any[], duration: number) => TakeNote[]
) => {
  const previewVideoRef = useRef<HTMLVideoElement | null>(null);
  const recordingIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const mediaStreamRef = useRef<MediaStream | null>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const recordedChunksRef = useRef<Blob[]>([]);
  const recordingTimeRef = useRef(0);
  const pendingTakeRef = useRef<PendingTake | null>(null);

  const clearRecordingInterval = useCallback(() => {
    if (recordingIntervalRef.current) {
      clearInterval(recordingIntervalRef.current);
      recordingIntervalRef.current = null;
    }
  }, []);

  const stopCameraTracks = useCallback((stream?: MediaStream | null) => {
    stream?.getTracks().forEach((track) => {
      track.stop();
    });
  }, []);

  const attachStreamToPreview = useCallback(async (stream: MediaStream) => {
    const preview = previewVideoRef.current;
    if (!preview) return;

    preview.srcObject = stream;
    preview.muted = true;
    preview.playsInline = true;

    try {
      await preview.play();
    } catch {
      // لا نرفع خطأ لأن بعض بيئات الاختبار تمنع التشغيل التلقائي.
    }
  }, []);

  const requestCameraAccess = useCallback(async (): Promise<MediaStream | null> => {
    if (typeof navigator === "undefined" || !navigator.mediaDevices?.getUserMedia) {
      const errorMessage = "هذه البيئة لا تدعم الوصول المباشر إلى الكاميرا والميكروفون.";
      showNotification("error", errorMessage);
      return null;
    }

    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: {
          facingMode: "user",
          width: { ideal: 1280 },
          height: { ideal: 720 },
        },
        audio: true,
      });
      stopCameraTracks(mediaStreamRef.current);
      mediaStreamRef.current = stream;
      await attachStreamToPreview(stream);
      showNotification("success", "تم تفعيل الكاميرا والميكروفون بنجاح.");
      return stream;
    } catch {
      const errorMessage = "تعذر الوصول إلى الكاميرا أو الميكروفون. تحقق من الأذونات ثم أعد المحاولة.";
      showNotification("error", errorMessage);
      return null;
    }
  }, [attachStreamToPreview, showNotification, stopCameraTracks]);

  const finalizeRecordedTake = useCallback(
    (pendingTake: PendingTake) => {
      const duration = Math.max(recordingTimeRef.current, 1);
      const primaryChunk = recordedChunksRef.current[0];
      const blob =
        recordedChunksRef.current.length > 0
          ? new Blob(recordedChunksRef.current, {
              type: pendingTake.mimeType || (primaryChunk?.type ?? "video/webm"),
            })
          : null;
      const videoUrl = blob && typeof URL.createObjectURL === "function" ? URL.createObjectURL(blob) : undefined;

      if (blob && videoUrl) {
        markTakeExportable(pendingTake.id);
      }

      const insights = buildTakeInsights({
        durationSeconds: duration,
        scriptText,
        teleprompterUsed: pendingTake.teleprompterUsed,
        hadRetake: takes.some((take) => take.source === "captured"),
      });

      const take: Take = {
        id: pendingTake.id,
        name: pendingTake.name,
        duration,
        recordedAt: pendingTake.recordedAt,
        notes: createNotesFromInsights(insights.notes, duration),
        score: insights.score,
        status: "completed",
        mimeType: blob?.type ?? pendingTake.mimeType,
        source: "captured",
        ...(videoUrl ? { videoUrl } : {}),
      };

      setTakes((previous) => [take, ...previous]);
      setNotesTakeId(take.id);
      setComparisonView((previous) => ({
        ...previous,
        leftTakeId: take.id,
        rightTakeId:
          previous.leftTakeId && previous.leftTakeId !== take.id
            ? previous.leftTakeId
            : previous.rightTakeId && previous.rightTakeId !== take.id
              ? previous.rightTakeId
              : previous.leftTakeId,
      }));
      pendingTakeRef.current = null;
      recordedChunksRef.current = [];

      if (blob) {
        showNotification("success", `تم حفظ ${take.name} وتوليد تقييمه المحلي بنجاح.`);
        return;
      }

      showNotification("error", "انتهى التسجيل لكن المتصفح لم يسلم ملف فيديو قابلاً للتصدير.");
    },
    [markTakeExportable, scriptText, showNotification, takes, setTakes, setNotesTakeId, setComparisonView, buildTakeInsights, createNotesFromInsights]
  );

  const startRecording = useCallback(async () => {
    if (!scriptText.trim()) {
      showNotification("error", "أدخل نصاً قبل بدء التسجيل.");
      return;
    }

    let stream = mediaStreamRef.current;
    if (!stream) {
      stream = await requestCameraAccess();
    }

    if (!stream) return;

    if (typeof MediaRecorder === "undefined") {
      showNotification("error", "المتصفح الحالي لا يدعم MediaRecorder، لذا لا يمكن تسجيل فيديو فعلي.");
      return;
    }

    const preferredMimeType = pickSupportedMimeType(RECORDING_MIME_CANDIDATES);
    let recorder: MediaRecorder;

    try {
      recorder = preferredMimeType
        ? new MediaRecorder(stream, { mimeType: preferredMimeType })
        : new MediaRecorder(stream);
    } catch {
      recorder = new MediaRecorder(stream);
    }

    recordedChunksRef.current = [];
    clearRecordingInterval();
    recordingTimeRef.current = 0;

    const takeNumber = takes.filter((take) => take.source === "captured").length + 1;
    const pendingTake: PendingTake = {
      id: `take-${Date.now()}`,
      name: `Take ${takeNumber}`,
      recordedAt: new Date().toISOString(),
      mimeType: recorder.mimeType || preferredMimeType,
      teleprompterUsed: teleprompterSettings.autoScroll,
    };

    pendingTakeRef.current = pendingTake;
    recorder.ondataavailable = (event: BlobEvent) => {
      if (event.data && event.data.size > 0) {
        recordedChunksRef.current.push(event.data);
      }
    };
    recorder.onstop = () => {
      if (pendingTakeRef.current) {
        finalizeRecordedTake(pendingTakeRef.current);
      }
    };
    recorder.onerror = () => {
      pendingTakeRef.current = null;
      recordedChunksRef.current = [];
      showNotification("error", "تعذر إتمام التسجيل. حاول مرة أخرى.");
    };

    try {
      recorder.start(1000);
      mediaRecorderRef.current = recorder;
      startTeleprompter();
      recordingIntervalRef.current = setInterval(() => {
        recordingTimeRef.current += 1;
      }, 1000);
      showNotification("info", "بدأ التسجيل الفعلي ويمكنك إنهاؤه متى شئت.");
    } catch {
      pendingTakeRef.current = null;
      showNotification("error", "فشل بدء التسجيل في هذه البيئة رغم توفر الكاميرا.");
    }
  }, [clearRecordingInterval, finalizeRecordedTake, requestCameraAccess, scriptText, showNotification, startTeleprompter, takes, teleprompterSettings.autoScroll]);

  const stopRecording = useCallback(() => {
    const recorder = mediaRecorderRef.current;
    if (!recorder || recorder.state === "inactive") return;

    clearRecordingInterval();
    stopTeleprompter();
    showNotification("info", "جاري إنهاء الملف وتحليل التسجيل...");

    try {
      recorder.stop();
    } catch {
      pendingTakeRef.current = null;
      showNotification("error", "تعذر إيقاف التسجيل بشكل صحيح.");
    }
  }, [clearRecordingInterval, showNotification, stopTeleprompter]);

  return {
    previewVideoRef,
    mediaStreamRef,
    mediaRecorderRef,
    recordedChunksRef,
    recordingTimeRef,
    pendingTakeRef,
    requestCameraAccess,
    startRecording,
    stopRecording,
    stopCameraTracks,
  };
};
