import { useState, useMemo, useRef } from "react";
import type { PersistedSelfTapeTake } from "../../../lib/self-tape";

type ActiveTool = "teleprompter" | "recorder" | "comparison" | "notes" | "export";
type CameraState = "idle" | "requesting" | "ready" | "error";
type NotificationState = {
  type: "success" | "error" | "info";
  message: string;
} | null;
type NoteType = "emotion" | "delivery" | "timing" | "movement" | "improvement";
type NoteSeverity = "positive" | "neutral" | "needs_work";

interface TakeNote {
  id: string;
  timestamp: number;
  type: NoteType;
  content: string;
  severity: NoteSeverity;
  autoGenerated: boolean;
}

interface Take extends PersistedSelfTapeTake {
  notes: TakeNote[];
  videoUrl?: string;
}

interface TeleprompterSettings {
  speed: number;
  fontSize: number;
  mirrorMode: boolean;
  highlightCurrentLine: boolean;
  autoScroll: boolean;
  countdownSeconds: number;
}

interface ExportSettings {
  quality: "casting" | "high" | "medium";
  format: "mp4" | "mov" | "webm";
  includeSlate: boolean;
  slateDuration: number;
  actorName: string;
  projectName: string;
  roleName: string;
  agencyName: string;
}

interface ComparisonView {
  leftTakeId: string | null;
  rightTakeId: string | null;
  syncPlayback: boolean;
}

interface PendingTake {
  id: string;
  name: string;
  recordedAt: string;
  mimeType: string;
  teleprompterUsed: boolean;
}

export const useSelfTapeState = (initialTakes: Take[]) => {
  const [activeTool, setActiveTool] = useState<ActiveTool>("teleprompter");
  const [notification, setNotification] = useState<NotificationState>(null);
  const [teleprompterSettings, setTeleprompterSettings] = useState<TeleprompterSettings>({
    speed: 50,
    fontSize: 32,
    mirrorMode: false,
    highlightCurrentLine: true,
    autoScroll: true,
    countdownSeconds: 5,
  });
  const [teleprompterRunning, setTeleprompterRunning] = useState(false);
  const [teleprompterPosition, setTeleprompterPosition] = useState(0);
  const [countdown, setCountdown] = useState(0);
  const [cameraState, setCameraState] = useState<CameraState>("idle");
  const [cameraError, setCameraError] = useState("");
  const [isRecording, setIsRecording] = useState(false);
  const [isFinalizingTake, setIsFinalizingTake] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [comparisonViewState, setComparisonView] = useState<ComparisonView>({
    leftTakeId: null,
    rightTakeId: null,
    syncPlayback: true,
  });
  const [exportSettings, setExportSettings] = useState<ExportSettings>({
    quality: "casting",
    format: "webm",
    includeSlate: true,
    slateDuration: 5,
    actorName: "",
    projectName: "",
    roleName: "",
    agencyName: "",
  });
  const [exportingTakeId, setExportingTakeId] = useState<string | null>(null);
  const [exportProgress, setExportProgress] = useState(0);
  const [notesTakeIdState, setNotesTakeId] = useState<string | null>(null);
  const [manualNoteDrafts, setManualNoteDrafts] = useState<Record<string, string>>({});
  const [manualNoteTypes, setManualNoteTypes] = useState<Record<string, NoteType>>({});
  const [exportableTakeIds, setExportableTakeIds] = useState<Set<string>>(() => new Set());

  const previewVideoRef = useRef<HTMLVideoElement | null>(null);
  const recordingIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const teleprompterIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const countdownIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const mediaStreamRef = useRef<MediaStream | null>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const recordedChunksRef = useRef<Blob[]>([]);
  const recordingTimeRef = useRef(0);
  const pendingTakeRef = useRef<PendingTake | null>(null);
  const blobRegistryRef = useRef<Map<string, Blob>>(new Map());
  const sessionUrlRegistryRef = useRef<Map<string, string>>(new Map());

  const availableTakes = useMemo(() => initialTakes.filter((take) => take.status !== "recording"), [initialTakes]);
  const notesTakeId = useMemo(() => {
    if (availableTakes.length === 0) return null;
    if (notesTakeIdState && availableTakes.some((take) => take.id === notesTakeIdState)) {
      return notesTakeIdState;
    }
    return availableTakes[0]?.id ?? null;
  }, [availableTakes, notesTakeIdState]);
  const comparisonView = useMemo<ComparisonView>(() => {
    const takeIds = new Set(availableTakes.map((take) => take.id));
    const nextLeft = comparisonViewState.leftTakeId && takeIds.has(comparisonViewState.leftTakeId)
      ? comparisonViewState.leftTakeId
      : (availableTakes[0]?.id ?? null);
    const nextRight = comparisonViewState.rightTakeId && takeIds.has(comparisonViewState.rightTakeId)
      ? comparisonViewState.rightTakeId
      : (availableTakes.find((take) => take.id !== nextLeft)?.id ?? null);
    return { ...comparisonViewState, leftTakeId: nextLeft, rightTakeId: nextRight };
  }, [availableTakes, comparisonViewState]);
  const totalDuration = useMemo(() => availableTakes.reduce((sum, take) => sum + take.duration, 0), [availableTakes]);
  const bestScore = useMemo(() => Math.max(...availableTakes.map((take) => take.score ?? 0), 0), [availableTakes]);
  const bestExportableTake = useMemo(() => {
    return [...availableTakes]
      .filter((take) => exportableTakeIds.has(take.id))
      .sort((left, right) => (right.score ?? 0) - (left.score ?? 0))[0];
  }, [availableTakes, exportableTakeIds]);

  return {
    // State
    activeTool,
    setActiveTool,
    notification,
    setNotification,
    teleprompterSettings,
    setTeleprompterSettings,
    teleprompterRunning,
    setTeleprompterRunning,
    teleprompterPosition,
    setTeleprompterPosition,
    countdown,
    setCountdown,
    cameraState,
    setCameraState,
    cameraError,
    setCameraError,
    isRecording,
    setIsRecording,
    isFinalizingTake,
    setIsFinalizingTake,
    recordingTime,
    setRecordingTime,
    comparisonViewState,
    setComparisonView,
    exportSettings,
    setExportSettings,
    exportingTakeId,
    setExportingTakeId,
    exportProgress,
    setExportProgress,
    notesTakeIdState,
    setNotesTakeId,
    manualNoteDrafts,
    setManualNoteDrafts,
    manualNoteTypes,
    setManualNoteTypes,
    exportableTakeIds,
    setExportableTakeIds,
    
    // Refs
    previewVideoRef,
    recordingIntervalRef,
    teleprompterIntervalRef,
    countdownIntervalRef,
    mediaStreamRef,
    mediaRecorderRef,
    recordedChunksRef,
    recordingTimeRef,
    pendingTakeRef,
    blobRegistryRef,
    sessionUrlRegistryRef,
    
    // Computed
    availableTakes,
    notesTakeId,
    comparisonView,
    totalDuration,
    bestScore,
    bestExportableTake,
  };
};
