"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { loadRemoteAppState, persistRemoteAppState } from "@/lib/app-state-client";
import {
  buildExportFileName,
  buildTakeInsights,
  inferExtensionFromMimeType,
  pickSupportedMimeType,
  readStoredSelfTapeTakes,
  SELF_TAPE_STORAGE_KEY,
  writeStoredSelfTapeTakes,
  type PersistedSelfTapeTake,
} from "../../lib/self-tape";
import {
  Header,
  Notification,
  ToolNavigation,
  TeleprompterPage,
  RecorderPage,
  ComparisonPage,
  NotesPage,
  ExportPage,
  useSelfTapeState,
  useCameraRecording,
  type ActiveTool,
  type CameraState,
  type NotificationState,
  type NoteType,
  type NoteSeverity,
  type TakeNote,
  type Take,
  type TeleprompterSettings,
  type ExportSettings,
  type ComparisonView,
  type PendingTake,
  type SelfTapeSuiteSnapshot,
} from "./studio";

const RECORDING_MIME_CANDIDATES = [
  "video/webm;codecs=vp9,opus",
  "video/webm;codecs=vp8,opus",
  "video/webm",
];
const EMPTY_CAPTIONS_TRACK = "data:text/vtt;charset=utf-8,WEBVTT%0A";

const NOTE_TYPE_LABELS: Record<NoteType, string> = {
  emotion: "💫 عاطفة",
  delivery: "🎤 إلقاء",
  timing: "⏱️ توقيت",
  movement: "🎭 حركة",
  improvement: "💡 تحسين",
};

const NOTE_TYPE_COLOR: Record<NoteType, string> = {
  emotion: "bg-pink-500/20 text-pink-300",
  delivery: "bg-blue-500/20 text-blue-300",
  timing: "bg-purple-500/20 text-purple-300",
  movement: "bg-orange-500/20 text-orange-300",
  improvement: "bg-cyan-500/20 text-cyan-300",
};

const SAMPLE_SCRIPT = `المشهد الأول - غرفة المعيشة - نهاراً

تدخل سارة الغرفة بخطوات متثاقلة، تحمل في يدها رسالة مفتوحة.

سارة: (تنظر للرسالة بصدمة)
لا... هذا لا يمكن أن يكون حقيقياً.
كيف يمكنه أن يفعل هذا بعد كل هذه السنوات؟

(تجلس على الأريكة، تمسك الرسالة بيدين مرتجفتين)

سارة: (بصوت مختنق)
ظننت أننا كنا عائلة...
ظننت أن الماضي قد انتهى.

(تنهض فجأة، تمشي نحو النافذة)

سارة: (بحزم)
لكنني لن أسمح لهذا أن يدمر ما بنيته.
لقد تغيرت... وسأثبت ذلك.`;

const SAMPLE_TAKES: Take[] = [
  {
    id: "sample-1",
    name: "Take 1 - أولي",
    duration: 125,
    recordedAt: "2025-01-15T10:30:00.000Z",
    notes: [
      {
        id: "sample-1-note-1",
        timestamp: 15,
        type: "emotion",
        content: "افتتاحية عاطفية قوية والصدمة مقروءة بصرياً.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-1-note-2",
        timestamp: 45,
        type: "timing",
        content: "يمكن إبطاء الإيقاع هنا قليلاً قبل الجملة الحاسمة.",
        severity: "needs_work",
        autoGenerated: true,
      },
      {
        id: "sample-1-note-3",
        timestamp: 92,
        type: "movement",
        content: "الانتقال نحو النافذة يخدم التصعيد جيداً.",
        severity: "positive",
        autoGenerated: true,
      },
    ],
    score: 78,
    status: "completed",
    source: "sample",
  },
  {
    id: "sample-2",
    name: "Take 2 - تحسين",
    duration: 132,
    recordedAt: "2025-01-15T10:45:00.000Z",
    notes: [
      {
        id: "sample-2-note-1",
        timestamp: 20,
        type: "emotion",
        content: "عمق عاطفي ممتاز في لحظة الانكسار الأولى.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-2-note-2",
        timestamp: 52,
        type: "timing",
        content: "الوقفة هنا مؤثرة ومضبوطة.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-2-note-3",
        timestamp: 100,
        type: "improvement",
        content: "النهاية تحتاج طبقة حسم أكثر وضوحاً.",
        severity: "neutral",
        autoGenerated: true,
      },
    ],
    score: 85,
    status: "completed",
    source: "sample",
  },
  {
    id: "sample-3",
    name: "Take 3 - نهائي",
    duration: 128,
    recordedAt: "2025-01-15T11:00:00.000Z",
    notes: [
      {
        id: "sample-3-note-1",
        timestamp: 18,
        type: "emotion",
        content: "الصدق العاطفي حاضر من البداية حتى الخاتمة.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-3-note-2",
        timestamp: 58,
        type: "delivery",
        content: "التلوين النغمي متوازن ويخدم الرهان الدرامي.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-3-note-3",
        timestamp: 96,
        type: "movement",
        content: "لغة الجسد واضحة ومنضبطة داخل الكادر.",
        severity: "positive",
        autoGenerated: true,
      },
    ],
    score: 92,
    status: "completed",
    source: "sample",
  },
];

function delay(milliseconds: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function cloneSampleTakes(): Take[] {
  return SAMPLE_TAKES.map((take) => ({
    ...take,
    notes: take.notes.map((note) => ({ ...note })),
  }));
}

function formatTime(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const remainder = seconds % 60;
  return `${minutes.toString().padStart(2, "0")}:${remainder
    .toString()
    .padStart(2, "0")}`;
}

function formatRecordedAt(value: string): string {
  return new Date(value).toLocaleString("ar-EG", {
    hour: "2-digit",
    minute: "2-digit",
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function toPersistedTake(take: Take): PersistedSelfTapeTake {
  const { videoUrl: _videoUrl, mimeType, score, ...baseTake } = take;

  return {
    ...baseTake,
    ...(typeof mimeType === "string" ? { mimeType } : {}),
    ...(typeof score === "number" ? { score } : {}),
  };
}

function createNotesFromInsights(
  notes: {
    type: "timing" | "delivery" | "improvement";
    severity: NoteSeverity;
    content: string;
  }[],
  duration: number
): TakeNote[] {
  const safeDuration = Math.max(duration, 1);
  const slots = Math.max(notes.length, 1);

  return notes.map((note, index) => ({
    id: `note-${Date.now()}-${index}`,
    timestamp: clamp(
      Math.round((safeDuration / slots) * (index + 0.5)),
      0,
      safeDuration
    ),
    type: note.type,
    severity: note.severity,
    content: note.content,
    autoGenerated: true,
  }));
}

function getSeverityContainerClass(severity: NoteSeverity): string {
  switch (severity) {
    case "positive":
      return "bg-green-500/10 border-green-500/30";
    case "needs_work":
      return "bg-yellow-500/10 border-yellow-500/30";
    default:
      return "bg-black/14 border-purple-500/30";
  }
}

function getScoreColor(score: number | undefined): string {
  if (!score) {
    return "text-white/55";
  }

  if (score >= 85) {
    return "text-green-400";
  }

  if (score >= 70) {
    return "text-yellow-400";
  }

  return "text-red-400";
}

function loadInitialTakes(): Take[] {
  const fallback = cloneSampleTakes().map(toPersistedTake);
  return readStoredSelfTapeTakes(fallback).map((take) => ({
    ...take,
    notes: take.notes.map((note) => ({ ...note })),
  }));
}

export const SelfTapeSuite: React.FC = () => {
  const {
    activeTool,
    setActiveTool,
    scriptText,
    setScriptText,
    takes,
    setTakes,
    isRemoteStateReady,
    notification,
    setNotification,
    teleprompterSettings,
    setTeleprompterSettings,
    teleprompterRunning,
    setTeleprompterRunning,
    teleprompterPosition,
    setTeleprompterPosition,
    countdown,
    setCountdown,
    exportSettings,
    setExportSettings,
    comparisonViewState,
    setComparisonView,
    notesTakeIdState,
    setNotesTakeId,
    manualNoteDrafts,
    setManualNoteDrafts,
    manualNoteTypes,
    setManualNoteTypes,
    exportableTakeIds,
    setExportableTakeIds,
    exportingTakeId,
    setExportingTakeId,
    exportProgress,
    setExportProgress,
    startTeleprompter,
    stopTeleprompter,
    resetTeleprompter,
    addManualNote,
    deleteTake,
    exportTake,
    showNotification,
  } = useSelfTapeState();

  const {
    cameraState,
    cameraError,
    isRecording,
    isFinalizingTake,
    recordingTime,
    previewVideoRef,
    mediaCaptureSupported,
    requestCameraAccess,
    startRecording,
    stopRecording,
  } = useCameraRecording({
    scriptText,
    teleprompterSettings,
    takes,
    setTakes,
    setNotesTakeId,
    setComparisonView,
    startTeleprompter,
    stopTeleprompter,
    showNotification,
    markTakeExportable: (takeId: string) => {
      setExportableTakeIds((previous) => {
        if (previous.has(takeId)) {
          return previous;
        }
        const next = new Set(previous);
        next.add(takeId);
        return next;
      });
    },
  });
  const availableTakes = useMemo(
    () => takes.filter((take) => take.status !== "recording"),
    [takes]
  );
  const notesTakeId = useMemo(() => {
    if (availableTakes.length === 0) {
      return null;
    }
    if (
      notesTakeIdState &&
      availableTakes.some((take) => take.id === notesTakeIdState)
    ) {
      return notesTakeIdState;
    }
    return availableTakes[0]?.id ?? null;
  }, [availableTakes, notesTakeIdState]);
  const comparisonView = useMemo<ComparisonView>(() => {
    const takeIds = new Set(availableTakes.map((take) => take.id));
    const nextLeft =
      comparisonViewState.leftTakeId &&
      takeIds.has(comparisonViewState.leftTakeId)
        ? comparisonViewState.leftTakeId
        : (availableTakes[0]?.id ?? null);
    const nextRight =
      comparisonViewState.rightTakeId &&
      takeIds.has(comparisonViewState.rightTakeId)
        ? comparisonViewState.rightTakeId
        : (availableTakes.find((take) => take.id !== nextLeft)?.id ?? null);

    return {
      ...comparisonViewState,
      leftTakeId: nextLeft,
      rightTakeId: nextRight,
    };
  }, [availableTakes, comparisonViewState]);
  const totalDuration = useMemo(
    () => availableTakes.reduce((sum, take) => sum + take.duration, 0),
    [availableTakes]
  );
  const bestScore = useMemo(
    () => Math.max(...availableTakes.map((take) => take.score ?? 0), 0),
    [availableTakes]
  );
  const bestExportableTake = useMemo(() => {
    return [...availableTakes]
      .filter((take) => exportableTakeIds.has(take.id))
      .sort((left, right) => (right.score ?? 0) - (left.score ?? 0))[0];
  }, [availableTakes, exportableTakeIds]);
  const promptLines = useMemo(
    () =>
      scriptText
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean),
    [scriptText]
  );
  const currentPromptLine = useMemo(() => {
    if (promptLines.length === 0) {
      return "أدخل نصاً لعرضه على التلقين.";
    }

    const lineIndex = clamp(
      Math.floor((teleprompterPosition / 100) * promptLines.length),
      0,
      promptLines.length - 1
    );
    return promptLines[lineIndex] ?? promptLines[0] ?? "";
  }, [promptLines, teleprompterPosition]);

  const leftTake = availableTakes.find(
    (take) => take.id === comparisonView.leftTakeId
  );
  const rightTake = availableTakes.find(
    (take) => take.id === comparisonView.rightTakeId
  );

  return (
    <div
      className="min-h-screen bg-gradient-to-bl from-black/14 via-purple-900 to-black/14"
      dir="rtl"
    >
      <Header
        storageKey={SELF_TAPE_STORAGE_KEY}
        onNavigateBack={() => {
          window.location.href = "/actorai-arabic";
        }}
      />

      <Notification notification={notification} />

      <main className="container mx-auto px-4 py-6">
        <ToolNavigation activeTool={activeTool} setActiveTool={setActiveTool} />

        {activeTool === "teleprompter" && (
          <TeleprompterPage
            scriptText={scriptText}
            setScriptText={setScriptText}
            teleprompterSettings={teleprompterSettings}
            setTeleprompterSettings={setTeleprompterSettings}
            teleprompterRunning={teleprompterRunning}
            teleprompterPosition={teleprompterPosition}
            countdown={countdown}
            startTeleprompter={startTeleprompter}
            stopTeleprompter={stopTeleprompter}
            resetTeleprompter={resetTeleprompter}
          />
        )}

        {activeTool === "recorder" && (
          <RecorderPage
            cameraState={cameraState}
            cameraError={cameraError}
            isRecording={isRecording}
            isFinalizingTake={isFinalizingTake}
            recordingTime={recordingTime}
            previewVideoRef={previewVideoRef}
            mediaCaptureSupported={mediaCaptureSupported}
            availableTakes={availableTakes}
            bestScore={bestScore}
            totalDuration={totalDuration}
            exportableTakeIds={exportableTakeIds}
            currentPromptLine={currentPromptLine}
            requestCameraAccess={requestCameraAccess}
            startRecording={startRecording}
            stopRecording={stopRecording}
            resetTeleprompter={resetTeleprompter}
            deleteTake={deleteTake}
            exportTake={exportTake}
            setActiveTool={setActiveTool}
            setNotesTakeId={setNotesTakeId}
            formatTime={formatTime}
            formatRecordedAt={formatRecordedAt}
            getScoreColor={getScoreColor}
          />
        )}

        {activeTool === "comparison" && (
          <ComparisonPage
            availableTakes={availableTakes}
            comparisonView={comparisonView}
            setComparisonView={setComparisonView}
            leftTake={leftTake}
            rightTake={rightTake}
            formatRecordedAt={formatRecordedAt}
            formatTime={formatTime}
            getScoreColor={getScoreColor}
          />
        )}

        {activeTool === "notes" && (
          <NotesPage
            availableTakes={availableTakes}
            notesTakeId={notesTakeId}
            setNotesTakeId={setNotesTakeId}
            manualNoteDrafts={manualNoteDrafts}
            setManualNoteDrafts={setManualNoteDrafts}
            manualNoteTypes={manualNoteTypes}
            setManualNoteTypes={setManualNoteTypes}
            addManualNote={addManualNote}
            formatTime={formatTime}
            getScoreColor={getScoreColor}
            getSeverityContainerClass={getSeverityContainerClass}
          />
        )}

        {activeTool === "export" && (
          <ExportPage
            exportSettings={exportSettings}
            setExportSettings={setExportSettings}
            exportingTakeId={exportingTakeId}
            exportProgress={exportProgress}
            availableTakes={availableTakes}
            exportableTakeIds={exportableTakeIds}
            bestExportableTake={bestExportableTake}
            exportTake={exportTake}
            formatTime={formatTime}
          />
        )}
      </main>

      <footer className="mt-8 border-t border-purple-500/30 bg-black/30">
        <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 py-6 md:flex-row">
          <p className="text-sm text-white/55">
            Self-Tape Suite © 2025 - جزء من منصة ActorAI العربية
          </p>
          <div className="flex items-center gap-4">
            <Badge
              variant="outline"
              className="border-purple-500/50 text-purple-300"
            >
              تخزين محلي + مزامنة خلفية
            </Badge>
            <Badge
              variant="outline"
              className="border-green-500/50 text-green-300"
            >
              v2
            </Badge>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default SelfTapeSuite;
